version: '3.6'
services:

  petstore_server:
    build:
      context: .
      dockerfile: microservices/petstore/petstore_server/Dockerfile
      target: service
    command: uvicorn openapi_server.main:app --host 0.0.0.0 --port 8080

  personal_page_server:
    build:
      context: .
      dockerfile: microservices/personal_page/personal_page_server/Dockerfile
      target: service
    command: uvicorn openapi_server:app --host 0.0.0.0 --port 8080
    environment:
      PETSTORE_SERVER_HOST: http://petstore_server
      PETSTORE_SERVER_PORT: 8080

  request_personal_page:
    build:
      context: .
      dockerfile: sample_client/Dockerfile
    command: /bin/bash ./request_personal_page.sh
