version: '3.6'
services:
  petstore:
    build:
      context: .
      dockerfile: microservices/petstore/petstore_server/Dockerfile
      target: service
    ports:
      - "8080:8080"
    command: uvicorn openapi_server.main:app --host 0.0.0.0 --port 8080

# pip install -e microservices/petstore/client-python-httpx/petstore_httpx_client
